### ISSUE TITLE
Getting the Module Error

### ISSUE THREAD

**Issue by ashishbharadwaj100** [seekwhencer/node-jetson-webcam#1]
After giving the command 
sudo npm run dev

I am getting this error please help me

> node-jetson-webcam@0.0.1 dev /home/ashish/node-jetson-webcam
> export NODE_ENV=default && node --experimental-modules index.js  

(node:15560) ExperimentalWarning: The ESM module loader is experimental.
/home/ashish/node-jetson-webcam/index.js:1
(function (exports, require, module, __filename, __dirname) { import Globals from './lib/Globals.js';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at createDynamicModule (internal/loader/ModuleRequest.js:52:15)
    at setExecutor (internal/loader/ModuleWrap.js:40:23)
    at file:///home/ashish/node-jetson-webcam/index.js:8:36

npm ERR! Linux 4.9.140-tegra
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! node-jetson-webcam@0.0.1 dev: `export NODE_ENV=default && node --experimental-modules index.js  `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-jetson-webcam@0.0.1 dev script 'export NODE_ENV=default && node --experimental-modules index.js  '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-jetson-webcam package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     export NODE_ENV=default && node --experimental-modules index.js  
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-jetson-webcam
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-jetson-webcam
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ashish/node-jetson-webcam/npm-debug.log

**Comment by ashishbharadwaj100** [comment]
root@ashish:/home/ashish/node-jetson-webcam# npm run dev

> node-jetson-webcam@0.0.1 dev /home/ashish/node-jetson-webcam
> export NODE_ENV=default && node --experimental-modules index.js  

(node:10100) ExperimentalWarning: The ESM module loader is experimental.
/home/ashish/node-jetson-webcam/index.js:1
import Globals from './lib/Globals.js';
       ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at createDynamicModule (internal/modules/esm/translators.js:73:15)
    at Object.meta.done (internal/modules/esm/create_dynamic_module.js:40:9)
    at file:///home/ashish/node-jetson-webcam/index.js:9:13
    at ModuleJob.run (internal/modules/esm/module_job.js:95:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-jetson-webcam@0.0.1 dev: `export NODE_ENV=default && node --experimental-modules index.js  `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-jetson-webcam@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-31T13_49_06_621Z-debug.log

**Comment by ashishbharadwaj100** [comment]
This issue I have solved by a famous person Matthias by updating the node version.
(function (exports, require, module, __filename, __dirname) { import Globals from './lib/Globals.js';
^^^^^^
Link is given below for updating the node and npm
https://computingforgeeks.com/how-to-install-nodejs-on-ubuntu-debian-linux-mint/

**Comment by ashishbharadwaj100** [comment]
But Right now I am stuck in this error 

npm run dev

> node-jetson-webcam@0.0.1 dev /home/ashish/data/node-jetson-webcam
> export NODE_ENV=default && node --experimental-modules index.js  

(node:8554) ExperimentalWarning: The ESM module loader is experimental.
[ 10:29:53 - 1.8.2019 ] APPCONFIG INIT default
[ 10:29:53 - 1.8.2019 ] 
[ 10:29:53 - 1.8.2019 ] //////////////////
[ 10:29:53 - 1.8.2019 ] RUNNING: node-jetson-webcam
[ 10:29:53 - 1.8.2019 ] VERSION: 0.0.1
[ 10:29:53 - 1.8.2019 ] ENVIRONMENT: default
[ 10:29:53 - 1.8.2019 ] /////////
[ 10:29:53 - 1.8.2019 ] 
[ 10:29:54 - 1.8.2019 ] CAMERA INIT First Cam
[ 10:29:55 - 1.8.2019 ] CAMERA First Cam CAPABILITIES FOR: /dev/video0 
 [video4linux2,v4l2 @ 0x55818005d0] Raw       :     yuyv422 :           YUYV 4:2:2 : 640x480 352x288 320x240 176x144 160x120
[ 10:29:57 - 1.8.2019 ] CAMERA First Cam STARTING /usr/bin/gst-launch-1.0 WITH OPTIONS -v -e v4l2src device=/dev/video0 ! image/jpeg,width=1280,height=720,type=video,framerate=24/1 ! jpegparse ! jpegdec ! videoconvert ! omxh264enc ! video/x-h264,stream-format=byte-stream ! h264parse ! mpegtsmux ! tcpserversink port=5100 host=0.0.0.0 buffers-min=10000
[ 10:29:57 - 1.8.2019 ] CAMERA First Cam STDOUT: Setting pipeline to PAUSED ...
[ 10:29:57 - 1.8.2019 ] CAMERA First Cam STDOUT: Pipeline is live and does not need PREROLL ...
[ 10:29:57 - 1.8.2019 ] CAMERA First Cam STDOUT: /GstPipeline:pipeline0/GstTCPServerSink:tcpserversink0: current-port = 5100
[ 10:29:57 - 1.8.2019 ] CAMERA First Cam STDOUT: Setting pipeline to PAUSED ...
Setting pipeline to READY ...
[ 10:29:57 - 1.8.2019 ] CAMERA First Cam STDERR: ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Internal data stream error.
Additional debug info:
gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
streaming stopped, reason not-negotiated (-4)
ERROR: pipeline doesn't want to preroll.
[ 10:29:57 - 1.8.2019 ] CAMERA First Cam STDOUT: Setting pipeline to NULL ...
[ 10:29:57 - 1.8.2019 ] CAMERA First Cam STDOUT: Freeing pipeline ...




My Default Configuration File I have edited and it looks like this just now I am trying with only one camera

[global]
name=My funky webcam controller

[api]
host=127.0.0.1
port=8080
root_endpoint=v1

[websocket]
root_endpoint=v1

[camera]
device=/dev/video0
name=default camera
bin=/usr/bin/gst-launch-1.0
ffmpeg_bin=/usr/bin/ffmpeg
width=640
height=480
framerate=30
quality=100
caps_delay=2000
ready_delay=2000
inputformat=YUY2
filebase=cam
host=127.0.0.1

[camera_1]
device=/dev/video0
name=First Cam
port=5100
mode=tcpmjpeg
width=1280
height=720
framerate=24

**Comment by seekwhencer** [comment]
something updated.... try the new version. works much better with stable network streams
and: you have to check if your camera support the resolution, framerate and the source type. per default it is mjpeg. i use 1280 x 720 at 30fps in mjpg. check your capabilities.

**Comment by seekwhencer** [comment]
the best results i've got with icecast2. the tcp stream is to instable for me in my setup. BUT: with icecast it works great! with a latency of a second or less... absolutely stable over 300mbits wifi from the jetson.
